import type { Doc, Id } from "../_generated/dataModel";
import type { ActionCtx } from "../_generated/server";
import { internal } from "../_generated/api";
import { slideFromCopy } from "../content/slideshowAdapter";
import { getSlideDimensions } from "../content/slideshowRenderer";
import {
  createArtifact,
  getArtifactsForRefs,
  reviewStatusForWorkflow,
  type StepOutputs,
  type WorkflowExecutionContext,
  type WorkflowStep,
} from "./execution";

type SlideshowSpec = {
  format?: string;
  aspectRatio?: string;
  hook?: string;
  caption?: string;
  slides?: Array<{
    index?: number;
    role?: string;
    headline?: string;
    body?: string;
    visualPrompt?: string;
    layout?: unknown;
  }>;
};

function isSlideshowSpec(value: unknown): value is SlideshowSpec {
  return Boolean(
    value &&
      typeof value === "object" &&
      Array.isArray((value as SlideshowSpec).slides)
  );
}

function getArtifactUrl(artifact: Doc<"artifacts">): string | undefined {
  if (artifact.storageUrl) return artifact.storageUrl;
  if (!artifact.data || typeof artifact.data !== "object") return undefined;

  const data = artifact.data as Record<string, unknown>;
  return typeof data.url === "string" ? data.url : undefined;
}

function getSlideIndexFromImageArtifact(artifact: Doc<"artifacts">): number | undefined {
  const parentTitle = artifact.title ?? "";
  const match = parentTitle.match(/Slide\s+(\d+)/i);
  if (match?.[1]) return Number(match[1]);

  if (!artifact.data || typeof artifact.data !== "object") return undefined;
  const data = artifact.data as Record<string, unknown>;
  const slide = data.slide;
  if (!slide || typeof slide !== "object") return undefined;

  const index = (slide as Record<string, unknown>).index;
  return typeof index === "number" ? index : undefined;
}

export async function executeRenderSlideshowStep(
  ctx: ActionCtx,
  context: WorkflowExecutionContext,
  step: WorkflowStep,
  outputs: StepOutputs
): Promise<Id<"artifacts">[]> {
  const slideSpecs = await getArtifactsForRefs(ctx, outputs, step.inputRefs, "slide_spec");
  const images = await getArtifactsForRefs(ctx, outputs, step.inputRefs, "image");
  const imageBySlideIndex = new Map<number, Doc<"artifacts">>();

  for (const image of images) {
    const slideIndex = getSlideIndexFromImageArtifact(image);
    if (slideIndex && !imageBySlideIndex.has(slideIndex)) {
      imageBySlideIndex.set(slideIndex, image);
    }
  }

  const artifactIds: Id<"artifacts">[] = [];
  for (const slideSpecArtifact of slideSpecs) {
    if (!isSlideshowSpec(slideSpecArtifact.data)) continue;

    const aspectRatio = slideSpecArtifact.data.aspectRatio ?? "9:16";
    const dimensions = getSlideDimensions(aspectRatio);
    const renderableSlides = (slideSpecArtifact.data.slides ?? []).map((slide, index) => {
      const slideIndex = slide.index ?? index + 1;
      const image = imageBySlideIndex.get(slideIndex);
      return {
        source: slide,
        image,
        imageUrl: image ? getArtifactUrl(image) : undefined,
        renderableSlide: slideFromCopy({
          index: slideIndex,
          role: slide.role,
          headline: slide.headline,
          body: slide.body,
          visualPrompt: slide.visualPrompt,
          layout: slide.layout,
        }),
      };
    });
    const slideshowSpec = {
      format: "slideshow",
      title: slideSpecArtifact.title || slideSpecArtifact.data.hook || "Generated slideshow",
      caption: slideSpecArtifact.data.caption ?? "",
      aspectRatio,
      dimensions,
      exportSettings: {
        previewMimeType: "image/png",
        publishMimeType: "image/jpeg",
        width: dimensions.width,
        height: dimensions.height,
      },
      creativeBrief: slideSpecArtifact.data.hook ?? "",
      strategy: {
        narrativePattern: "Workflow-generated slideshow",
        targetSlideCount: renderableSlides.length,
        reasoning: "Generated by workflow render step.",
        visualStyle: context.brand.visualStyle ?? "Readable social carousel",
        tone: context.brand.voice ?? "direct",
        layoutStrategy: {
          hookPlacement: "center",
          contentPlacement: "center",
        },
      },
      slides: renderableSlides.map(({ renderableSlide, imageUrl, image }) => ({
        ...renderableSlide,
        status: "active",
        dimensions,
        backgroundImageUrl: imageUrl,
        sourceImageArtifactId: image?._id ? String(image._id) : undefined,
        renderVersion: 1,
        renderStatus: "pending",
        updatedAt: Date.now(),
      })),
    };
    const slideshowId = await ctx.runMutation(internal.content.slideshows.createFromRunner, {
      userId: context.run.userId,
      brandId: context.run.brandId,
      socialAccountId: context.run.socialAccountId,
      workflowId: context.workflow._id,
      workflowRunId: context.run._id,
      title: slideshowSpec.title,
      caption: slideshowSpec.caption,
      status: "saved",
      spec: slideshowSpec,
      renderVersion: 1,
      revisionHistory: [
        {
          type: "workflow_create",
          at: Date.now(),
          sourceSlideSpecArtifactId: slideSpecArtifact._id,
        },
      ],
    });

    for (const { image, renderableSlide } of renderableSlides) {
      artifactIds.push(
        await ctx.runAction(internal.content.rendering.renderSlideForWorkflow, {
          userId: context.run.userId,
          brandId: context.run.brandId,
          workflowId: context.workflow._id,
          workflowRunId: context.run._id,
          slideshowId,
          slideId: renderableSlide.slideId,
          specArtifactId: slideSpecArtifact._id,
          parentArtifactIds: [
            slideSpecArtifact._id,
            ...(image ? [image._id] : []),
          ],
          reviewStatus: reviewStatusForWorkflow(context),
        })
      );
    }

    await ctx.runMutation(internal.content.slideshows.updateFromRunner, {
      slideshowId,
      userId: context.run.userId,
      spec: {
        ...slideshowSpec,
        slides: slideshowSpec.slides.map((slide) => ({
          ...slide,
          renderStatus: "succeeded" as const,
        })),
      },
    });
  }

  return artifactIds;
}

export async function executeImagePromptStep(
  ctx: ActionCtx,
  context: WorkflowExecutionContext,
  step: WorkflowStep,
  outputs: StepOutputs
): Promise<Id<"artifacts">[]> {
  const slideSpecs = await getArtifactsForRefs(ctx, outputs, step.inputRefs, "slide_spec");
  const artifactIds: Id<"artifacts">[] = [];

  for (const slideSpecArtifact of slideSpecs) {
    if (!isSlideshowSpec(slideSpecArtifact.data)) continue;

    for (const slide of slideSpecArtifact.data.slides ?? []) {
      if (!slide.visualPrompt?.trim()) continue;

      artifactIds.push(
        await createArtifact(ctx, context, step, {
          type: "image_prompt",
          title: `Slide ${slide.index ?? artifactIds.length + 1} image prompt`,
          data: {
            prompt: slide.visualPrompt,
            slide,
            aspectRatio: slideSpecArtifact.data.aspectRatio,
            hook: slideSpecArtifact.data.hook,
          },
          prompt: slide.visualPrompt,
          parentArtifactIds: [slideSpecArtifact._id],
          reviewStatus: reviewStatusForWorkflow(context),
        })
      );
    }
  }

  return artifactIds;
}
